a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('So tem espaço? ', a.isspace())
print('E um numero? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Esta em maiuscula?', a.isupper())
print('Esta em minusculas? ', a.islower())
print('Esta capitalizada? ', a.istitle())